resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/raleygroup/concourse-demo.git
      branch: master

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
  - task: test
    file: sources/pipeline/test.yml
  - task: publish test report
    file: sources/pipeline/publishReport.yml
